import type { TestProfile } from '@/types/profile.type'

export const TEST_PROFILES: TestProfile[] = [
  {
    id: 1,
    name: 'Анна Смирнова',
    joinedAt: '2018-04-14',
    avatarUrl: 'https://randomuser.me/api/portraits/women/44.jpg',
    avatarFallback: 'АС',
    accentColor: '#00aaff',
    purchases: 12,
    sales: 7,
    favoriteCategory: 'Электроника',
    largestPurchase: {
      title: 'Смартфон',
      category: 'Электроника',
      price: 118000,
      date: '2026-03-12',
    },
    smallestPurchase: {
      title: 'Чехол для телефона',
      category: 'Аксессуары',
      price: 490,
      date: '2026-01-17',
    },
    annualSpending: 246850,
  },
  {
    id: 2,
    name: 'Михаил Орлов',
    joinedAt: '2021-09-03',
    avatarUrl: 'https://randomuser.me/api/portraits/men/32.jpg',
    avatarFallback: 'МО',
    accentColor: '#965eeb',
    purchases: 5,
    sales: 14,
    favoriteCategory: 'Хобби и отдых',
    largestPurchase: {
      title: 'Акустическая гитара',
      category: 'Музыкальные инструменты',
      price: 64900,
      date: '2026-05-21',
    },
    smallestPurchase: {
      title: 'Комплект струн',
      category: 'Музыкальные инструменты',
      price: 850,
      date: '2026-02-06',
    },
    annualSpending: 112300,
  },
  {
    id: 3,
    name: 'Елена Коваль',
    joinedAt: '2016-11-28',
    avatarUrl: 'https://randomuser.me/api/portraits/women/68.jpg',
    avatarFallback: 'ЕК',
    accentColor: '#04e061',
    purchases: 21,
    sales: 3,
    favoriteCategory: 'Для дома и дачи',
    largestPurchase: {
      title: 'Робот-пылесос',
      category: 'Бытовая техника',
      price: 54990,
      date: '2026-04-09',
    },
    smallestPurchase: {
      title: 'Набор полотенец',
      category: 'Текстиль',
      price: 1290,
      date: '2026-07-02',
    },
    annualSpending: 198740,
  },
  {
    id: 4,
    name: 'Даниил Волков',
    joinedAt: '2023-02-19',
    avatarUrl: 'https://randomuser.me/api/portraits/men/75.jpg',
    avatarFallback: 'ДВ',
    accentColor: '#ff4053',
    purchases: 8,
    sales: 9,
    favoriteCategory: 'Транспорт',
    largestPurchase: {
      title: 'Комплект колёс',
      category: 'Запчасти',
      price: 84000,
      date: '2026-03-30',
    },
    smallestPurchase: {
      title: 'Держатель для телефона',
      category: 'Автоаксессуары',
      price: 990,
      date: '2026-01-24',
    },
    annualSpending: 173500,
  },
]
