import type { TestProfile } from '@/types/profile.type'

export const TEST_PROFILES: TestProfile[] = [
  {
    id: 1,
    name: 'Анна Смирнова',
    joinedAt: '2018-04-14',
    avatarUrl: 'https://randomuser.me/api/portraits/women/44.jpg',
    avatarFallback: 'АС',
    accentColor: '#00aaff',
    chatsCount: 43,
    favoriteCategory: 'Электроника',
    metrics: {
      activeDays: 163,
      city: 'Москва',
      createdListings: 25,
      favoriteListings: 32,
      likes: 148,
      rating: 4.9,
      reviews: 17,
    },
    purchases: [
      { title: 'Смартфон', category: 'Электроника', price: 118000, date: '2026-03-12' },
      { title: 'Наушники', category: 'Аудио', price: 12990, date: '2026-05-04' },
      { title: 'Чехол для телефона', category: 'Аксессуары', price: 490, date: '2026-01-17' },
    ],
    sales: [
      { title: 'Планшет', category: 'Электроника', price: 28500, date: '2026-02-20', inquiriesCount: 14 },
      { title: 'Кресло', category: 'Для дома', price: 7500, date: '2026-06-18', inquiriesCount: 9 },
    ],
    listingViews: [
      { title: 'Ноутбук для работы', category: 'Ноутбуки', likes: 12, viewedAt: '2026-07-10T20:15', viewCount: 7 },
      { title: 'Фотоаппарат', category: 'Фототехника', likes: 8, viewedAt: '2026-06-29T13:40', viewCount: 3 },
    ],
  },
  {
    id: 2,
    name: 'Михаил Орлов',
    joinedAt: '2021-09-03',
    avatarUrl: 'https://randomuser.me/api/portraits/men/32.jpg',
    avatarFallback: 'МО',
    accentColor: '#965eeb',
    chatsCount: 51,
    favoriteCategory: 'Хобби и отдых',
    metrics: {
      activeDays: 109,
      city: 'Казань',
      createdListings: 31,
      favoriteListings: 19,
      likes: 86,
      rating: 4.8,
      reviews: 12,
    },
    purchases: [
      { title: 'Акустическая гитара', category: 'Музыкальные инструменты', price: 64900, date: '2026-05-21' },
      { title: 'Велосипедный шлем', category: 'Спорт', price: 5400, date: '2026-04-02' },
      { title: 'Комплект струн', category: 'Музыкальные инструменты', price: 850, date: '2026-02-06' },
    ],
    sales: [
      { title: 'Игровая консоль', category: 'Игры', price: 32000, date: '2026-03-04', inquiriesCount: 21 },
      { title: 'Сноуборд', category: 'Спорт', price: 18500, date: '2026-01-26', inquiriesCount: 17 },
    ],
    listingViews: [
      { title: 'Электрогитара', category: 'Музыкальные инструменты', likes: 15, viewedAt: '2026-07-17T21:05', viewCount: 11 },
      { title: 'Палатка на 4 человека', category: 'Туризм', likes: 6, viewedAt: '2026-06-12T09:25', viewCount: 4 },
    ],
  },
  {
    id: 3,
    name: 'Елена Коваль',
    joinedAt: '2016-11-28',
    avatarUrl: 'https://randomuser.me/api/portraits/women/68.jpg',
    avatarFallback: 'ЕК',
    accentColor: '#04e061',
    chatsCount: 27,
    favoriteCategory: 'Для дома и дачи',
    metrics: {
      activeDays: 202,
      city: 'Санкт-Петербург',
      createdListings: 16,
      favoriteListings: 47,
      likes: 219,
      rating: 5,
      reviews: 28,
    },
    purchases: [
      { title: 'Робот-пылесос', category: 'Бытовая техника', price: 54990, date: '2026-04-09' },
      { title: 'Торшер', category: 'Мебель и интерьер', price: 8990, date: '2026-05-28' },
      { title: 'Набор полотенец', category: 'Текстиль', price: 1290, date: '2026-07-02' },
    ],
    sales: [
      { title: 'Детская кроватка', category: 'Товары для детей', price: 11200, date: '2026-02-14', inquiriesCount: 18 },
      { title: 'Кофемашина', category: 'Бытовая техника', price: 19700, date: '2026-06-03', inquiriesCount: 11 },
    ],
    listingViews: [
      { title: 'Диван', category: 'Мебель и интерьер', likes: 23, viewedAt: '2026-07-24T18:30', viewCount: 9 },
      { title: 'Увлажнитель воздуха', category: 'Бытовая техника', likes: 10, viewedAt: '2026-07-08T11:45', viewCount: 5 },
    ],
  },
  {
    id: 4,
    name: 'Даниил Волков',
    joinedAt: '2023-02-19',
    avatarUrl: 'https://randomuser.me/api/portraits/men/75.jpg',
    avatarFallback: 'ДВ',
    accentColor: '#ff4053',
    chatsCount: 36,
    favoriteCategory: 'Транспорт',
    metrics: {
      activeDays: 87,
      city: 'Екатеринбург',
      createdListings: 22,
      favoriteListings: 14,
      likes: 63,
      rating: 4.7,
      reviews: 9,
    },
    purchases: [
      { title: 'Комплект колёс', category: 'Запчасти', price: 84000, date: '2026-03-30' },
      { title: 'Видеорегистратор', category: 'Автоэлектроника', price: 15400, date: '2026-06-11' },
      { title: 'Держатель для телефона', category: 'Автоаксессуары', price: 990, date: '2026-01-24' },
    ],
    sales: [
      { title: 'Горный велосипед', category: 'Спорт', price: 46800, date: '2026-04-16', inquiriesCount: 26 },
      { title: 'Автомагнитола', category: 'Автоэлектроника', price: 9400, date: '2026-05-08', inquiriesCount: 13 },
    ],
    listingViews: [
      { title: 'Кроссовый мотоцикл', category: 'Мототехника', likes: 19, viewedAt: '2026-07-22T19:10', viewCount: 8 },
      { title: 'Багажник на крышу', category: 'Автоаксессуары', likes: 7, viewedAt: '2026-07-03T08:55', viewCount: 4 },
    ],
  },
]
