import type { TestProfile } from '@/types/profile.type'

export const TEST_PROFILES: TestProfile[] = [
  {
    id: 1,
    name: 'Анна Смирнова',
    memberSince: 'На Авито с 2018 года',
    avatarUrl: 'https://randomuser.me/api/portraits/women/44.jpg',
    avatarFallback: 'АС',
    accentColor: '#00aaff',
    purchases: 12,
    topPurchaseCategory: 'Электроника',
    sales: 7,
    saleMessages: 24,
    favorites: 18,
    chats: 43,
  },
  {
    id: 2,
    name: 'Михаил Орлов',
    memberSince: 'На Авито с 2021 года',
    avatarUrl: 'https://randomuser.me/api/portraits/men/32.jpg',
    avatarFallback: 'МО',
    accentColor: '#965eeb',
    purchases: 5,
    topPurchaseCategory: 'Хобби',
    sales: 14,
    saleMessages: 38,
    favorites: 9,
    chats: 51,
  },
  {
    id: 3,
    name: 'Елена Коваль',
    memberSince: 'На Авито с 2016 года',
    avatarUrl: 'https://randomuser.me/api/portraits/women/68.jpg',
    avatarFallback: 'ЕК',
    accentColor: '#04e061',
    purchases: 21,
    topPurchaseCategory: 'Для дома',
    sales: 3,
    saleMessages: 11,
    favorites: 32,
    chats: 27,
  },
  {
    id: 4,
    name: 'Даниил Волков',
    memberSince: 'На Авито с 2023 года',
    avatarUrl: 'https://randomuser.me/api/portraits/men/75.jpg',
    avatarFallback: 'ДВ',
    accentColor: '#ff4053',
    purchases: 8,
    topPurchaseCategory: 'Транспорт',
    sales: 9,
    saleMessages: 31,
    favorites: 14,
    chats: 36,
  },
]
